-- New tables to be added to your existing schema

-- DROP TABLE GEE_BASE_FUNCTIONS         ;
-- DROP TABLE GEE_BASE_FUNCTIONS_PARAMS  ;
-- DROP TABLE GEE_ENV_CONFIG             ;
-- DROP TABLE GEE_FIELD_CLASSES          ;
-- DROP TABLE GEE_FIELDS                 ;
-- DROP TABLE GEE_FLOW_CONNECTIONS       ;
-- DROP TABLE GEE_FLOW_EXECUTION_LOG     ;
-- DROP TABLE GEE_FLOW_EXECUTION_STEPS   ;
-- DROP TABLE GEE_FLOW_NODES             ;
-- DROP TABLE GEE_FLOW_VALIDATION_RULES  ;
-- DROP TABLE GEE_FLOW_VERSIONS          ;
-- DROP TABLE GEE_FLOWS                  ;
-- DROP TABLE GEE_RULES_DEF              ;
-- DROP TABLE GEE_RULES_DEF_PARAMS       ;
-- DROP TABLE GEE_RULES_GROUPS           ;
-- DROP TABLE GEE_STATION_RULE_GROUPS    ;
-- DROP TABLE GEE_STATIONS               ;
-- DROP TABLE GEE_TABLES                 ;
-- DROP TABLE GEE_ACTIVE_CONNECTIONS     ;

-- Stores the overall flow definitions


CREATE TABLE GEE_FIELD_CLASSES (
    GFC_ID INTEGER PRIMARY KEY,
    GFC_IS INTEGER,
    FIELD_CLASS_NAME TEXT NOT NULL,
    CLASS_TYPE TEXT NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT
)
CREATE TABLE GEE_FIELDS (
    GF_ID INTEGER PRIMARY KEY,
    GFC_ID INTEGER,
    GF_NAME TEXT NOT NULL,
    GF_TYPE TEXT NOT NULL,
    GF_SIZE INTEGER,
    GF_PRECISION_SIZE INTEGER,
    GF_DEFAULT_VALUE TEXT,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    GF_DESCRIPTION TEXT,
    FOREIGN KEY (GFC_ID) REFERENCES GEE_FIELD_CLASSES(GFC_ID)
)
CREATE TABLE GEE_BASE_FUNCTIONS (
    GBF_ID INTEGER PRIMARY KEY,
    FUNC_NAME TEXT NOT NULL,
    PARAM_COUNT INTEGER,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT
)
CREATE TABLE GEE_BASE_FUNCTIONS_PARAMS (
    GBFP_ID INTEGER PRIMARY KEY,
    GBF_ID INTEGER,
    GBF_SEQ INTEGER,
    PARAM_NAME TEXT NOT NULL,
    PARAM_TYPE TEXT NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT,
    FOREIGN KEY (GBF_ID) REFERENCES GEE_BASE_FUNCTIONS(GBF_ID)
)
CREATE TABLE GEE_RULES_GROUPS (
    GRG_ID INTEGER PRIMARY KEY,
    GROUP_NAME TEXT NOT NULL,
    COND_TYPE TEXT,
    GRG_ID_PARENT INTEGER,
    GRG_ID_CHILD INTEGER,
    COND_GRG_ID_START INTEGER,
    COND_GRG_ID_END INTEGER,
    ACT_GRG_ID_START INTEGER,
    ACT_GRG_ID_END INTEGER,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT
)
CREATE TABLE GEE_RULES_DEF (
    GRD_ID INTEGER PRIMARY KEY,
    GBF_ID INTEGER,
    GBF_SEQ INTEGER,
    PARAM_NAME TEXT NOT NULL,
    PARAM_TYPE TEXT NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT,
    FOREIGN KEY (GBF_ID) REFERENCES GEE_BASE_FUNCTIONS(GBF_ID)
)
CREATE TABLE GEE_RULES_DEF_PARAMS (
    GRD_ID INTEGER PRIMARY KEY,
    GRG_ID INTEGER,
    GF_ID INTEGER,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    GF_DESCRIPTION TEXT,
    FOREIGN KEY (GRG_ID) REFERENCES GEE_RULES_GROUPS(GRG_ID),
    FOREIGN KEY (GF_ID) REFERENCES GEE_FIELDS(GF_ID)
)
CREATE TABLE GEE_FLOWS (
    FLOW_ID INTEGER PRIMARY KEY,
    FLOW_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    VERSION INTEGER DEFAULT 1,
    STATUS TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'ACTIVE', 'ARCHIVED'
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    CREATED_BY TEXT,
    LAST_EDITED_BY TEXT
)
CREATE TABLE GEE_FLOW_VERSIONS (
    VERSION_ID INTEGER PRIMARY KEY,
    FLOW_ID INTEGER,
    VERSION_NUMBER INTEGER,
    FLOW_DATA TEXT, -- JSON snapshot of the entire flow
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY TEXT,
    COMMENTS TEXT,
    FOREIGN KEY (FLOW_ID) REFERENCES GEE_FLOWS(FLOW_ID)
)
CREATE TABLE GEE_FLOW_NODES (
    NODE_ID INTEGER PRIMARY KEY,
    FLOW_ID INTEGER,
    NODE_TYPE TEXT NOT NULL, -- 'STATION', 'RULE_GROUP', or 'RULE'
    REFERENCE_ID INTEGER, -- ID of the referenced entity (e.g., GRG_ID for rule groups)
    PARENT_NODE_ID INTEGER, -- For hierarchical structure (e.g., rule group inside station)
    POSITION_X REAL, -- X coordinate on canvas
    POSITION_Y REAL, -- Y coordinate on canvas
    WIDTH REAL,
    HEIGHT REAL,
    LABEL TEXT,
    CUSTOM_SETTINGS TEXT, -- JSON field for additional settings
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    FOREIGN KEY (FLOW_ID) REFERENCES GEE_FLOWS(FLOW_ID),
    FOREIGN KEY (PARENT_NODE_ID) REFERENCES GEE_FLOW_NODES(NODE_ID)
)
CREATE TABLE GEE_FLOW_CONNECTIONS (
    CONNECTION_ID INTEGER PRIMARY KEY,
    FLOW_ID INTEGER,
    SOURCE_NODE_ID INTEGER,
    TARGET_NODE_ID INTEGER,
    CONNECTION_TYPE TEXT, -- 'SUCCESS', 'FAILURE', 'DEFAULT', 'CONDITIONAL'
    CONDITION_EXPRESSION TEXT, -- Optional condition for the connection
    LABEL TEXT,
    STYLE_SETTINGS TEXT, -- JSON field for styling (color, line style, etc.)
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    FOREIGN KEY (FLOW_ID) REFERENCES GEE_FLOWS(FLOW_ID),
    FOREIGN KEY (SOURCE_NODE_ID) REFERENCES GEE_FLOW_NODES(NODE_ID),
    FOREIGN KEY (TARGET_NODE_ID) REFERENCES GEE_FLOW_NODES(NODE_ID)
)
CREATE TABLE GEE_STATIONS (
    STATION_ID INTEGER PRIMARY KEY,
    STATION_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    STATION_TYPE TEXT, -- e.g., 'INPUT', 'PROCESS', 'OUTPUT'
    ICON TEXT, -- Icon reference for the UI
    COLOR_CODE TEXT, -- For custom color in the UI
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME
)
CREATE TABLE GEE_STATION_RULE_GROUPS (
    MAPPING_ID INTEGER PRIMARY KEY,
    STATION_ID INTEGER,
    GRG_ID INTEGER,
    SEQUENCE INTEGER,
    IS_REQUIRED BOOLEAN DEFAULT 0,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME,
    FOREIGN KEY (STATION_ID) REFERENCES GEE_STATIONS(STATION_ID),
    FOREIGN KEY (GRG_ID) REFERENCES GEE_RULES_GROUPS(GRG_ID)
)
CREATE TABLE GEE_FLOW_VALIDATION_RULES (
    RULE_ID INTEGER PRIMARY KEY,
    RULE_NAME TEXT NOT NULL,
    RULE_TYPE TEXT, -- 'CONNECTIVITY', 'COMPLETENESS', 'LOGIC', etc.
    RULE_EXPRESSION TEXT, -- SQL or other expression for validation
    DESCRIPTION TEXT,
    SEVERITY TEXT, -- 'ERROR', 'WARNING', 'INFO'
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME
)
CREATE TABLE GEE_FLOW_EXECUTION_LOG (
    LOG_ID INTEGER PRIMARY KEY,
    FLOW_ID INTEGER,
    FLOW_VERSION INTEGER,
    EXECUTION_START DATETIME,
    EXECUTION_END DATETIME,
    STATUS TEXT, -- 'SUCCESS', 'FAILURE', 'PARTIAL'
    INPUT_DATA TEXT, -- JSON
    OUTPUT_DATA TEXT, -- JSON
    ERROR_DETAILS TEXT,
    FOREIGN KEY (FLOW_ID) REFERENCES GEE_FLOWS(FLOW_ID)
)
CREATE TABLE GEE_FLOW_EXECUTION_STEPS (
    STEP_ID INTEGER PRIMARY KEY,
    LOG_ID INTEGER,
    NODE_ID INTEGER,
    SEQUENCE INTEGER,
    START_TIME DATETIME,
    END_TIME DATETIME,
    STATUS TEXT, -- 'SUCCESS', 'FAILURE', 'SKIPPED'
    INPUT_DATA TEXT, -- JSON
    OUTPUT_DATA TEXT, -- JSON
    ERROR_DETAILS TEXT,
    FOREIGN KEY (LOG_ID) REFERENCES GEE_FLOW_EXECUTION_LOG(LOG_ID),
    FOREIGN KEY (NODE_ID) REFERENCES GEE_FLOW_NODES(NODE_ID)
)
CREATE TABLE GEE_TABLES(
    GEC_ID INTEGER PRIMARY KEY,
    TABLE_NAME TEXT NOT NULL,
    TABLE_TYPE TEXT NOT NULL,
    QUERY TEXT,
    UPDATE_DATE DATETIME,
    DESCRIPTION TEXT
)
CREATE TABLE GEE_ENV_CONFIG (
    GT_ID INTEGER PRIMARY KEY,
    ENV_NAME TEXT NOT NULL,
    DB_NAME TEXT NOT NULL,
    DB_PASSWORD TEXT,
    DB_INSTANCE TEXT,
	DB_TYPE TEXT,
    DB_PORT INTEGER,
    LINUX_USER TEXT,
    LINUX_PASSWORD TEXT,
    LINUX_HOST TEXT
)
CREATE TABLE GEE_ACTIVE_CONNECTIONS (
    HANDLE TEXT PRIMARY KEY,
    CONFIG_ID INTEGER NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS TEXT DEFAULT 'active', APP_RUNTIME_ID TEXT,
    FOREIGN KEY (CONFIG_ID) REFERENCES GEE_ENV_CONFIG (GT_ID)
)
CREATE TABLE GRG_RULES (
                RULE_ID INTEGER PRIMARY KEY,
                RULE_NAME TEXT NOT NULL,
                RULE_TYPE TEXT,
                DESCRIPTION TEXT,
                CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
                UPDATE_DATE DATETIME
            )
CREATE TABLE GRG_RULE_GROUPS (
                GRG_ID INTEGER PRIMARY KEY,
                GROUP_NAME TEXT NOT NULL,
                COND_TYPE TEXT,
                GRG_ID_PARENT INTEGER,
                DESCRIPTION TEXT,
                COND_GRG_ID_START INTEGER,
                ACT_GRG_ID_START INTEGER,
                CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
                UPDATE_DATE DATETIME,
                FOREIGN KEY (GRG_ID_PARENT) REFERENCES GRG_RULE_GROUPS(GRG_ID)
            )
CREATE TABLE GRG_RULE_GROUP_RULES (
                MAPPING_ID INTEGER PRIMARY KEY,
                GRG_ID INTEGER,
                RULE_ID INTEGER,
                SEQUENCE INTEGER,
                CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
                UPDATE_DATE DATETIME,
                FOREIGN KEY (GRG_ID) REFERENCES GRG_RULE_GROUPS(GRG_ID),
                FOREIGN KEY (RULE_ID) REFERENCES GRG_RULES(RULE_ID)
            )